Repository mayadata-io/kubera-ui, pull requests merged in 2020-12, with the labels that each got.

#78 Update0.2.10
  package.json
  src/core/Modal/Modal.stories.tsx
  src/core/Modal/Modal.tsx
  src/core/Modal/base.ts
Labels: size/XS

#79 Fix InputField autofill bug
  package.json
  src/core/InputField/styles.ts
Labels: READY TO MERGE, size/S

#80 New api v0.3.0
  jest.config.js
  package.json
  src/core/Button/ButtonFilled/ButtonFilled.stories.tsx
  src/core/Button/ButtonFilled/ButtonFilled.tsx
  src/core/Button/ButtonGroup/ButtonGroup.tsx
  src/core/Button/ButtonOutlined/ButtonOutlined.tsx
  src/core/Button/ToggleButton/ToggleButton.stories.tsx
  src/core/Button/ToggleButton/ToggleButton.tsx
  src/core/Button/ToggleButton/__tests__/ToggleButton.test.tsx
  src/core/InputField/InputField.tsx
  src/core/KuberaCard/KuberaCard.tsx
  src/core/Link/Link.tsx
  src/core/Modal/Modal.tsx
  src/core/Pills/BasicPills/BasicPills.tsx
  src/core/Pills/LightPills/LightPills.tsx
  src/core/Pills/OutlinedPills/OutlinedPills.tsx
  src/core/ProgressBar/ProgressBar.tsx
  src/core/ProgressBar/base.ts
  src/core/ProgressBar/index.ts
  src/core/RadioButton/RadioButton.tsx
  src/core/RadioButton/index.ts
  src/core/Search/Search.tsx
  src/theme/index.ts
Labels: READY TO MERGE

#81 Additional Graph Colors for Chaos + Sidebar Menu color update
  package.json
  src/theme/base.ts
  src/theme/kubera-chaos.ts
  src/theme/kubera-core.tsx
Labels: READY TO MERGE, size/L
