Repository mayadata-io/kubera-ui, pull requests merged in 2020-10, with the labels that each got.

#10 Added Themes for Kubera Core and Portal + Updated Stories
  README.md
  src/core/Button/ButtonFilled/ButtonFilled.stories.tsx
  src/core/Button/ButtonOutlined/ButtonOutlined.stories.tsx
  src/core/Button/ToggleButton/ToggleButton.stories.tsx
  src/theme/ThemeProvider.tsx
  src/theme/base.ts
  src/theme/kubera-core.tsx
  src/theme/kubera-portal.tsx
Labels: enhancement

#25 Adding CircleCI for Build and Test checks
  .circleci/config.yml
  package-lock.json
  package.json
  rollup.config.js
  yarn.lock
Labels: enhancement

#38 Updated Linting setup in Circle CI
  .circleci/config.yml
Labels: bug

#7 Pills componet
  src/core/Pills/BasicPills/BasicPills.stories.tsx
  src/core/Pills/BasicPills/BasicPills.tsx
  src/core/Pills/BasicPills/__tests__/BasicPills.test.tsx
  src/core/Pills/BasicPills/index.ts
  src/core/Pills/BasicPills/style.ts
  src/core/Pills/LightPills/LightPills.stories.tsx
  src/core/Pills/LightPills/LightPills.tsx
  src/core/Pills/LightPills/__tests__/LightPills.test.tsx
  src/core/Pills/LightPills/index.ts
  src/core/Pills/LightPills/style.ts
  src/core/Pills/base.ts
  src/core/Pills/index.ts
  src/core/index.ts
Labels: PR: Changes Requested, adding-component, enhancement, size/L

#45 Added Chromatic UI to Kubera UI storybook
  .gitignore
  package.json
  yarn.lock
Labels: enhancement, size/XXL

#46 Added Chromatic UI GitHub Action
  .github/workflows/chromatic.yml
Labels: enhancement, size/S

#42 Text component
  src/core/Text/Header/Header.stories.tsx
  src/core/Text/Header/Header.tsx
  src/core/Text/Header/__tests__/Header.test.tsx
  src/core/Text/Header/index.ts
  src/core/Text/Header/styles.ts
  src/core/Text/Paragraph/Paragraph.stories.tsx
  src/core/Text/Paragraph/Paragraph.tsx
  src/core/Text/Paragraph/__tests__/Paragraph.test.tsx
  src/core/Text/Paragraph/index.ts
  src/core/Text/Paragraph/styles.ts
  src/core/Text/Subtitle/Subtitle.stories.tsx
  src/core/Text/Subtitle/Subtitle.tsx
  src/core/Text/Subtitle/__tests__/Subtitle.test.tsx
  src/core/Text/Subtitle/index.ts
  src/core/Text/Subtitle/styles.ts
  src/core/Text/base.ts
  src/core/Text/index.ts
  src/core/index.ts
Labels: adding-component, enhancement, looks-good, size/L

#41 search initial look
  package.json
  src/core/Search/Search.stories.tsx
  src/core/Search/Search.tsx
  src/core/Search/__tests__/Search.test.tsx
  src/core/Search/base.ts
  src/core/Search/index.ts
  src/core/Search/styles.ts
  src/core/index.ts
  yarn.lock
Labels: adding-component, enhancement, looks-good, size/L

#43 ButtonGroup initial look
  src/core/ButtonGroup/ButtonGroup.stories.tsx
  src/core/ButtonGroup/ButtonGroup.tsx
  src/core/ButtonGroup/__tests__/ButtonGroup.test.tsx
  src/core/ButtonGroup/base.ts
  src/core/ButtonGroup/index.ts
  src/core/ButtonGroup/styles.ts
  src/core/index.ts
Labels: READY TO MERGE, adding-component, enhancement, looks-good, size/L

#40 Link component
  package.json
  src/core/Link/Link.stories.tsx
  src/core/Link/Link.tsx
  src/core/Link/__tests__/Link.test.tsx
  src/core/Link/base.ts
  src/core/Link/index.ts
  src/core/Link/styles.ts
  src/core/index.ts
  yarn.lock
Labels: adding-component, enhancement, looks-good, size/L

#28 Progress bar component
  src/core/ProgressBar/ProgressBar.stories.tsx
  src/core/ProgressBar/ProgressBar.tsx
  src/core/ProgressBar/__tests__/ProgressBar.test.tsx
  src/core/ProgressBar/index.tsx
  src/core/ProgressBar/styles.ts
  src/core/index.ts
Labels: adding-component, looks-good, size/L

#50 Added kubera graphs (experimental)
  package.json
  src/lab/Graphs/AreaGraph/AreaChart.tsx
  src/lab/Graphs/AreaGraph/AreaGraph.stories.tsx
  src/lab/Graphs/AreaGraph/AreaGraph.tsx
  src/lab/Graphs/AreaGraph/base.ts
  src/lab/Graphs/AreaGraph/index.ts
  src/lab/Graphs/index.ts
  src/lab/index.ts
  tsconfig.json
  yarn.lock
Labels: DO NOT MERGE, size/XXL

#6 Added Modal component
  src/core/Modal/Modal.stories.tsx
  src/core/Modal/Modal.tsx
  src/core/Modal/__tests__/Modal.test.tsx
  src/core/Modal/base.ts
  src/core/Modal/index.ts
  src/core/Modal/styles.ts
  src/core/index.ts
Labels: adding-component, enhancement, looks-good, size/L

#52 theme color fixes
  src/theme/kubera-chaos.ts
  src/theme/kubera-core.tsx
  src/theme/kubera-portal.tsx
  src/theme/kubera-propel.tsx
  src/theme/litmus-portal.ts
Labels: size/L

#54 updated version to v0.2.0 and added breakpoints
  package.json
  src/theme/base.ts
Labels: READY TO MERGE, size/S

#32 Radio button component
  src/core/RadioButton/RadioButton.stories.tsx
  src/core/RadioButton/__tests__/RadioButton.test.tsx
  src/core/RadioButton/base.ts
  src/core/RadioButton/index.tsx
  src/core/RadioButton/styles.ts
  src/core/index.ts
Labels: adding-component, enhancement, looks-good, size/L

#8 Tab component
  package.json
  src/core/Tabs/Tabs.stories.tsx
  src/core/Tabs/Tabs.tsx
  src/core/Tabs/__tests__/Tabs.test.tsx
  src/core/Tabs/base.ts
  src/core/Tabs/index.ts
  src/core/Tabs/styles.ts
  src/core/index.ts
  yarn.lock
Labels: PR: Review Requested, adding-component, enhancement, size/L

#55 Added Card component
  src/core/KuberaCard/KuberaCard.stories.tsx
  src/core/KuberaCard/KuberaCard.tsx
  src/core/KuberaCard/__tests__/KuberaCard.test.tsx
  src/core/KuberaCard/index.ts
  src/core/KuberaCard/styles.ts
  src/core/index.ts
Labels: PR: Changes Requested, adding-component, enhancement, size/L
