Repository mayadata-io/kubera-ui, pull requests merged in 2020-11, with the labels that each got.

#59 Updated Pills(Added Outlined Pills) + Added Text Variants
  src/core/Pills/OutlinedPills/OutlinedPills.stories.tsx
  src/core/Pills/OutlinedPills/OutlinedPills.tsx
  src/core/Pills/OutlinedPills/__tests__/OutlinedPills.test.tsx
  src/core/Pills/OutlinedPills/index.ts
  src/core/Pills/OutlinedPills/style.ts
  src/core/Pills/index.ts
  src/core/Text/Header/Header.stories.tsx
  src/core/Text/Header/Header.tsx
  src/core/Text/Header/styles.ts
  src/core/Text/Paragraph/Paragraph.stories.tsx
  src/core/Text/Paragraph/Paragraph.tsx
  src/core/Text/Paragraph/styles.ts
  src/core/Text/Subtitle/Subtitle.stories.tsx
  src/core/Text/Subtitle/Subtitle.tsx
  src/core/Text/Subtitle/styles.ts
  src/core/Text/base.ts
Labels: READY TO MERGE, enhancement, size/L

#60 Added new colors to the core theme and fixed Modal export
  package.json
  src/core/Button/ButtonFilled/styles.ts
  src/core/Button/ButtonOutlined/styles.ts
  src/core/Modal/Modal.stories.tsx
  src/core/Modal/Modal.tsx
  src/core/Modal/__tests__/Modal.test.tsx
  src/theme/base.ts
  src/theme/kubera-core.tsx
Labels: size/M

#61 Updated Additional Colors for Kubera Core
  src/core/RadioButton/__tests__/RadioButton.test.tsx
  src/theme/kubera-core.tsx
Labels: READY TO MERGE, enhancement, size/M

#64 updated version to 0.2.3
  package.json
Labels: size/XS

#66 updated colors for kubera portal
  package.json
  src/theme/base.ts
  src/theme/kubera-portal.tsx
Labels: READY TO MERGE, size/M

#67 imporved inputfield component
  package.json
  src/core/InputField/InputField.tsx
  src/core/InputField/styles.ts
Labels: size/S

#68 Update0.2.6
  package.json
  src/core/KuberaCard/KuberaCard.stories.tsx
  src/core/KuberaCard/KuberaCard.tsx
  src/core/KuberaCard/__tests__/KuberaCard.test.tsx
  src/core/KuberaCard/styles.ts
  src/core/Modal/Modal.stories.tsx
  src/core/Modal/Modal.tsx
  src/core/Modal/__tests__/Modal.test.tsx
  src/core/Modal/base.ts
  src/core/Modal/styles.ts
Labels: READY TO MERGE, size/L

#69 Legend table added along with CSS refactoring
  src/lab/Graphs/AreaGraph/index.ts
  src/lab/Graphs/LineAreaGraph/LegendTable.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.stories.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/PlotLineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/base.ts
  src/lab/Graphs/LineAreaGraph/index.ts
  src/lab/Graphs/LineAreaGraph/styles.ts
  src/lab/Graphs/LineAreaGraph/testData.ts
  src/lab/Graphs/index.ts
  src/lab/index.ts
Labels: size/L

#70 update v0.2.7
  package.json
Labels: size/XS

#73 Legend table metric name overflow fix
  src/lab/Graphs/LineAreaGraph/LegendTable.tsx
  src/lab/Graphs/LineAreaGraph/styles.ts
  src/lab/Graphs/LineAreaGraph/testData.ts
Labels: READY TO MERGE, size/M

#74 modified the Text components and lab exports
  package.json
  rollup.config.js
  src/core/Text/Header/Header.tsx
  src/core/Text/Header/styles.ts
  src/core/Text/Paragraph/Paragraph.tsx
  src/core/Text/Paragraph/styles.ts
  src/core/Text/Subtitle/Subtitle.tsx
  src/core/Text/Subtitle/styles.ts
  src/index.ts
  src/lab/Graphs/LineAreaGraph/LegendTable.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/PlotLineAreaGraph.tsx
  src/lab/Graphs/index.ts
  src/lab/Tabs/Tabs.tsx
  src/lab/index.ts
Labels: READY TO MERGE, size/L

#76 radialChart
  src/lab/Graphs/RadialChart/LegendTable.tsx
  src/lab/Graphs/RadialChart/RadialChart.tsx
  src/lab/Graphs/RadialChart/RaidalChart.stories.tsx
  src/lab/Graphs/RadialChart/base.ts
  src/lab/Graphs/RadialChart/index.ts
  src/lab/Graphs/RadialChart/styles.ts
  src/lab/Graphs/RadialChart/testRadialChartData.ts
Labels: size/L
