Repository mayadata-io/kubera-ui, pull requests merged in 2021-01, with the labels that each got.

#83 Update v0.3.2
  package.json
  src/theme/base.ts
Labels: size/S

#82 custom text
  package.json
  src/core/InputField/InputField.tsx
  src/core/InputField/styles.ts
  src/core/Text/EditableText/EditableText.stories.tsx
  src/core/Text/EditableText/EditableText.tsx
  src/core/Text/EditableText/__tests__/EditableText.test.tsx
  src/core/Text/EditableText/base.ts
  src/core/Text/EditableText/index.ts
  src/core/Text/EditableText/styles.ts
  src/core/Text/index.ts
Labels: PR: Changes Requested, READY TO MERGE, size/L

#84 Wt custom text prop update
  package.json
  src/core/InputField/styles.ts
  src/core/Text/EditableText/EditableText.stories.tsx
  src/core/Text/EditableText/EditableText.tsx
  src/core/Text/EditableText/styles.ts
Labels: PR: Changes Requested, READY TO MERGE, size/L

#85 LineAreaGraph update: eventSeries and ToolTip added
  package-lock.json
  package.json
  src/lab/Graphs/LineAreaGraph/ComputationGraph.tsx
  src/lab/Graphs/LineAreaGraph/LegendTable.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.stories.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/PlotLineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/base.ts
  src/lab/Graphs/LineAreaGraph/styles.ts
  src/lab/Graphs/LineAreaGraph/testData.ts
  src/theme/base.ts
  src/theme/kubera-chaos.ts
  src/theme/kubera-core.tsx
  src/theme/kubera-portal.tsx
  src/theme/kubera-propel.tsx
  src/theme/litmus-portal.ts
  yarn.lock
Labels: PR: Review Requested, READY TO MERGE

#86 patch 0.3.5
  package.json
Labels: size/XS

#89 LegendTable (new component) and RadialChart updated
  package.json
  src/lab/Graphs/LegendTable/LegendTable.stories.tsx
  src/lab/Graphs/LegendTable/LegendTable.tsx
  src/lab/Graphs/LegendTable/base.ts
  src/lab/Graphs/LegendTable/index.ts
  src/lab/Graphs/LegendTable/style.ts
  src/lab/Graphs/LegendTable/testData.ts
  src/lab/Graphs/LineAreaGraph/ComputationGraph.tsx
  src/lab/Graphs/LineAreaGraph/LegendTable.tsx
  src/lab/Graphs/LineAreaGraph/LineAreaGraph.stories.tsx
  src/lab/Graphs/LineAreaGraph/PlotLineAreaGraph.tsx
  src/lab/Graphs/LineAreaGraph/base.ts
  src/lab/Graphs/LineAreaGraph/styles.ts
  src/lab/Graphs/LineAreaGraph/testData.ts
  src/lab/Graphs/RadialChart/LegendTable.tsx
  src/lab/Graphs/RadialChart/RadialChart.tsx
  src/lab/Graphs/RadialChart/RaidalChart.stories.tsx
  src/lab/Graphs/RadialChart/base.ts
  src/lab/Graphs/RadialChart/styles.ts
  src/lab/Graphs/RadialChart/testData.ts
  src/lab/Graphs/RadialChart/testRadialChartData.ts
  src/lab/Graphs/index.ts
Labels: READY TO MERGE, size/XL
